### ISSUE TITLE
after install every   run gulp serve and  npm start  it shows  can't find dist/index.html

### ISSUE THREAD

**Issue by liu-kanghui** [datatypevoid/ng2-mean-webpack#3]

**Comment by datatypevoid** [comment]
Have you run any of the `build` commands yet—eg `npm run build` or `npm start`? The `dist` directory is created by `webpack` after it bundles everything up. Would you mind giving me a breakdown of what you have attempted so far? 

EDIT: Also what version of `npm` and `node` are you using, and your operating system?

**Comment by liu-kanghui** [comment]
Hey,  I didn't do any build command before. But, I just tried again.  
first I did `npm install`  it is all good.  then `npm run build` it built the dist folder. After that I did `npm start`and `node server`  everything looks good so far.  When I modify something in the template, the hot reloaded is working, but the change doesn't reflect on the page I guess because it is using the dist/index. 

I shut down the server, and delete the dist folder. 
follow your instruction for development I did  `npm start`& `gulp serve`in a different terminal.
It throws error 

MacBook-Air:ng2-mean-webpack-master kanghuiliu$ gulp serve
module.js:327
    throw err;
    ^
Error: Cannot find module 'globby'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)

Yesterday after it gave me the same error (cannot find the globby module)  I did **npm install globby**.
after that I did  `npm start` &`gulp serve` again,  it showed  can't fint  dist/index.

I was wondering if it uses dist/index.html   then every time I do a change in the src file how can it be watched?  

Node is  V4.3.1
Npm is  2.14.21
Mac 

Thanks a whole lot :)

**Comment by datatypevoid** [comment]
The way it works is `npm start` points to the `server:dev:hmr` command in `package.json`. This command uses `Webpack` to package all of your front-end code into a single `main.bundle.js` file that you see in `dist/`. It also creates an `index.html` file based on the `index.html` file in `src/` using some `Webpack` configurations. Whenever you save a change to something in the front-end, `Webpack` pushes the change to your browser after updating the `main.bundle.js` file. 

I have a Mac at home that I can do some debugging with later, but IIRC I had to update `npm` to version `3.x.x+` and `node` to the `5.x.x`\+ to get this working with something or the other. If you don't want to go through the trouble of reinstalling `node`, check out https://github.com/creationix/nvm for a great `node` version manager that will allow you to have multiple versions installed side-by-side.

Before you attempt that though can you build the front-end with `npm start` in one terminal, and then open another terminal and run `node server` to start the back end up, rather than `gulp serve`? I don't think that this will fix it, but just in case.

Nonetheless, keep me updated with what's happening on your end. I am stepping out for a couple of hours, but I will be back online shortly after I return.

**Comment by liu-kanghui** [comment]
Hiiii

 I just updated my node to V 5  and npm to version 3. + 

still  can't find dist/index   after I run  `npm start` and  `gulp serve`  or `node server`

but if i do `npm run build`  then`node server`   everything works  

But again changes won't be updated

**Comment by liu-kanghui** [comment]
I look up the  app/route.js

```
  // Route to handle all Angular requests
  app.get('*', (req, res) => {

    // Load our src/app.html file
    res.sendfile('./dist/index.html');
  });
};
```

this send /dist/index.html  
if I run  `npm start`&  `gulp serve` the dist folder is not built. 
and the hot module reload only watch for  the  src/ folder 

I am very new to this,  everything looks very complicated.  
I really wish that there is a tutorial or video that teaches newbie to set up everything from scratch.  
I am really having a hard time to understand how everything works together  

Really appreciate your help :)

**Comment by datatypevoid** [comment]
Alright, I am settling in for a while now. I am going to see what I can uncover. Let me know if anything changes on your end.

**Comment by datatypevoid** [comment]
@liu-kanghui Thank for being patient with me as well! I assure you I will figure out what is up, I use this pack in my day to day work no problem ;)

**Comment by datatypevoid** [comment]
@liu-kanghui I have done a little investigating so far and it seems that as you said, the `npm start` script isn't generating a `dist/` directory. I am still working on it from there.

**Comment by liu-kanghui** [comment]
Yeah,  thank you very much for this great repo.    Would it be possible for you to do a video recording teachs us how to set up everything from scratch (empty folder hahah),  from webpack typescript  gulp express to angular 2....   I am sure lots of people are as confused like I am .  :(      I am sure the video would be a great hit.   haahahaha

**Comment by datatypevoid** [comment]
@liu-kanghui I actually do have an interest in producing video tutorials similar to the ones you are talking about, but time is not on my side currently... hopefully in the near future though ;)

**Comment by datatypevoid** [comment]
@liu-kanghui The issue wasn't anything in the repo but was due to a flawed understanding of how the `webpack-dev-server` works on my part. The `webpack-dev-server` only builds the files in memory; this is useful for hot module reloading but not for our `Express` server. The reason this escaped under the radar for so long is because as long as you first run the `npm run build` command, the `Express` server will find all of the files it is looking for after the `build` completes and the `dist/` directory is created. This means that I never saw the error because I have a habit of running `npm run build` initially and not `npm start`. So to clarify:
1. Repo is updated with a lot of little things so I suggest updating first
2. Create the `config.json` object as the readme instructs
3. Run `npm install typings webpack-dev-server -g`
4. Run `npm install`
5. In a new terminal, run `npm run watch`—this will watch all files and build on change
6. In ANOTHER new terminal, run `npm start`—this will fire up the `webpack-dev-server` and give you hot module reloading. Note that this terminal is not strictly necessary, but you will have to manually reload your page upon every change that you make.
7. In the ORIGINAL terminal that you started in, run `gulp serve` to fire up the back-end and get everything working

I am going to update the README to reflect all of this after I make myself a little dinner. Cheers and let me know if you have any other problems!

**Comment by datatypevoid** [comment]
I have updated the `readme` and installed `concurrently` to run the scripts for `webpack` and `webpack-dev-server` in parallel in the same terminal with `npm start`. Make sure you run `npm run build` before you use `npm start` for the first time though! @liu-kanghui Let me know if everything works out on your end.

**Comment by liu-kanghui** [comment]
Alright!!!  everything works great.    Thank you very much.  finally I can go on to read the todo tutorial.  happy hahaha 

`create config.json`
`npm install typings webpack-dev-server -g`
`npm install concurrently -save`         (why not include in the package json??) 
`npm install`
`npm run watch    -- first terminal`
`npm start    -- second terminal`
`gulp serve   -- third terminal`

Why do we still use gulp?  can webpack do what gulp does in the repo?

**Comment by datatypevoid** [comment]
@liu-kanghui I am glad to hear it! Thanks for sticking it out with me. 

The purpose that `gulp` is serving here is to serve up our `server.js` file and watch all of the necessary files for the back-end and restart on any changes using `nodemon`. `Gulp` is a workflow automation tool; `webpack` takes modules with dependencies and bundles them as a static asset.

**Comment by liu-kanghui** [comment]
Hey David, I have a very silly question. 
How can I add external javascript file? 

for example like bootstrap.js   I put  it under the src/  folder.  and import it in the app.ts 
import '../boostrap.js' ;
but it throws me error like :  
 The only supported extensions are '.ts', '.tsx', '.d.ts'.

also how to add jquery?    I follow the instruction from the angular-webpack-start wiki--- how to add jquery  but it gives me error: 
Subsequent variable declarations must have the same type.  
Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.

Thanks in advance!

**Comment by datatypevoid** [comment]
No question is silly; questions are the only way to learn, whether internalized or externalized.

As far as `Bootstrap` goes, it is actually already included in the library. If you look at `src/index.html` it has 

```
<!-- load the latest and greatest Bootstrap 3 styles -->
  <link data-require="bootstrap-css@*" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
```

in the `<head>` which loads it just like any old html page would.

As far as importing a `Javascript` file into the front-end, you could rewrite it in `TypeScript` and then import it as a `.ts` file. It is best to export a `function` or `class` as I show in the tutorial with the different parts of the `Todo` component.

Other options can be explored here for starters: https://basarat.gitbooks.io/typescript/content/docs/types/migrating.html

As far as `jQuery` goes, I point you here as I haven't messed with `jQuery` in well over a year. For me, it is `Sass/CSS3` or bust ;p http://www.syntaxsuccess.com/viewarticle/using-jquery-with-angular-2.0

**Comment by liu-kanghui** [comment]
David you are awesome, I really appreciate your help

The problem is,  I am using other people's template for responsive blog design. 
He uses all these customized js file to style the blog and I have no clue how to include it and  make it work with current angular 2 structure. 

it is so easy with just html css and js  just include them in the `link`or `script` tag in index.html. now. I am so lost.    

I add this line in index.html and it works for css 
`<link rel="stylesheet" href="/assets/css/font-awesome.min.css">`
but the javascript just doesn't work at all.     It is not possible for me to rewrite these javascript files. :( 

![screen shot 2016-03-11 at 7 25 50 pm](https://cloud.githubusercontent.com/assets/13057188/13720490/23ea8236-e7bf-11e5-8c22-11dc37748678.png)
![screen shot 2016-03-11 at 7 26 02 pm](https://cloud.githubusercontent.com/assets/13057188/13720491/290789da-e7bf-11e5-9c8e-32c729bc774f.png)

**Comment by datatypevoid** [comment]
@liu-kanghui I will look into this as soon as I can for you. I have a few things to take care of before then, but I will get back to you soon.

**Comment by datatypevoid** [comment]
As far as `jQuery` goes this should help you @liu-kanghui :

```
npm install jquery --save-dev
typings install jquery --save --ambient

  plugins: [
    new webpack.ProvidePlugin({
      jQuery: 'jquery',
      $: 'jquery',
      jquery: 'jquery'
    })
  ]
```
