### ISSUE TITLE
how to change favicon

### ISSUE THREAD

**Issue by Perezmarc** [datatypevoid/ng2-mean-webpack#8]
Hello!
It's me again :/ ...
Just a quick question: how do you embed your favicon?

cause I added to my index
 `<link rel="icon" type="image/svg" sizes="32x32" href="/assets/icon/favicon.svg">
<meta name="msapplication-TileImage" content="/assets/icon/favicon.svg">`
and commented all others but I still see the angular favicon...

Thanks a lot!

**Comment by datatypevoid** [comment]
Just so you know, the project has switched names and continued at: https://github.com/datatypevoid/vulgar

It's probably because your browser is caching them locally and it doesn't realize it has changed. There are various ways to fix this explored here: https://stackoverflow.com/questions/2208933/how-do-i-force-a-favicon-refresh

Also, if you have support questions that aren't necessarily issues, we do have a support Slack that you can access here: http://www.davidniciforovic.com/wp-login.php?action=slack-invitation

Hope everything else is working out well for you!
